
["Fuel Items"]
	#Defines items that can be used as fuel
	#Format: [["item-id-1", amount-1], ["item-id-2", amount-2], ...etc]
	Boiler = [["minecraft:coal", 37], ["modestmining:coal_chunk", 5], ["minecraft:charcoal", 37], ["modestmining:charcoal_chunk", 5], ["modestmining:coke", 120], ["modestmining:coke_chunk", 37], ["minecraft:coal_block", 333], ["quark:charcoal_block", 333], ["modestmining:coke_block", 900], ["minecraft:magma_block", 333], ["minecraft:lava_bucket", 1000]]
	Icebox = [["minecraft:snowball", 37], ["minecraft:clay", 37], ["minecraft:snow_block", 333], ["minecraft:water_bucket", 333], ["minecraft:ice", 333], ["minecraft:packed_ice", 1000]]
	#Negative values indicate cold fuel
	Hearth = [["minecraft:coal", 37], ["modestmining:coal_chunk", 5], ["minecraft:charcoal", 37], ["modestmining:charcoal_chunk", 5], ["modestmining:coke", 120], ["modestmining:coke_chunk", 37], ["minecraft:coal_block", 333], ["quark:charcoal_block", 333], ["modestmining:coke_block", 900], ["minecraft:magma_block", 333], ["minecraft:lava_bucket", 1000], ["minecraft:snowball", -37], ["minecraft:clay", -37], ["minecraft:snow_block", -333], ["minecraft:water_bucket", -333], ["minecraft:ice", -333], ["minecraft:packed_ice", -1000]]
	#Potions containing any of these effects will not be allowed in the hearth
	#Format: ["effect_id", "effect_id", ...etc]
	"Blacklisted Potion Effects" = ["minecraft:instant_damage", "minecraft:instant_health"]
	#If true, potions can be used as fuel in the hearth
	#This gives all players in range the potion effect
	"Allow Potions in Hearth" = true

["Soulspring Lamp"]
	#Defines items that the Soulspring Lamp can use as fuel
	#Format: [["item-id-1", amount-1], ["item-id-2", amount-2], ...etc]
	"Fuel Items" = []
	#Defines the dimensions that the Soulspring Lamp can be used in
	#Format: ["dimension-id-1", "dimension-id-2", ...etc]
	"Valid Dimensions" = []

[Insulation]
	#Defines the items that can be used for insulating armor in the Sewing Table
	#Format: [["item_id", cold, hot], ["item_id", cold, hot], ...etc]
	#"item_id": The item's ID (i.e. "minecraft:iron_ingot"). Accepts tags with "#" (i.e. "#minecraft:wool").
	#"cold": The amount of cold insulation the item provides.
	#"hot": The amount of heat insulation the item provides.
	"Insulation Ingredients" = [["ecologics:penguin_feather", 1.0, 0.0], ["minecraft:feather", 0.5, 0.5], ["alexsmobs:emu_feather", 0.0, 1.0], ["modestmining:fiber", 0.0, 0.5], ["alexsmobs:raccoon_tail", 0.5, 0.5], ["farmersdelight:canvas", 0.5, 0.5], ["fundamentallyfixed:cloth", 0.5, 0.5], ["minecraft:white_wool", 1.9, 0.5], ["minecraft:white_carpet", 0.5, 0.1], ["minecraft:gray_wool", 1.0, -0.5], ["minecraft:gray_carpet", 0.5, 0.1], ["fundamentallyfixed:mammal_hide", 0.5, 0.5], ["naturalist:reptile_hide", 2, 0], ["cold_sweat:fur", 2.5, 0], ["alexsmobs:bison_fur_block", 12.0, 0.0], ["alexsmobs:bison_carpet", 5.5, 0], ["environmental:yak_hair", 1.0, 1.0], ["environmental:yak_hair_block", 6.0, 6.0], ["environmental:yak_hair_rug", 2.0, 2.0], ["minecraft:blue_wool", 1.0, 0.0], ["minecraft:blue_carpet", 0.5, 0.1], ["minecraft:leather", 1.5, 1.5], ["minecraft:light_blue_wool", 1.0, 0.0], ["minecraft:light_blue_carpet", 0.5, 0.1], ["cold_sweat:hoglin_hide", 0.0, 2.0], ["minecraft:leather_boots", 4.0, 4.0], ["minecraft:red_wool", 1.0, 0.0], ["minecraft:red_carpet", 0.5, 0.1], ["minecraft:leather_helmet", 4.0, 4.0], ["minecraft:yellow_wool", 1.0, 0.0], ["minecraft:yellow_carpet", 0.5, 0.1], ["minecraft:magenta_wool", 1.0, 0.0], ["minecraft:magenta_carpet", 0.5, 0.1], ["minecraft:brown_wool", 1.0, 0.0], ["minecraft:brown_carpet", 0.5, 0.1], ["minecraft:green_wool", 1.0, 0.0], ["minecraft:green_carpet", 0.5, 0.1], ["minecraft:black_wool", 1.0, -1.0], ["minecraft:black_carpet", 0.5, 0.1], ["minecraft:lime_wool", 1.0, 0.0], ["minecraft:lime_carpet", 0.5, 0.1], ["minecraft:pink_wool", 1.0, 0.0], ["minecraft:pink_carpet", 0.5, 0.1], ["minecraft:orange_wool", 1.0, 0.0], ["minecraft:orange_carpet", 0.5, 0.1], ["minecraft:purple_wool", 1.0, 0.0], ["minecraft:purple_carpet", 0.5, 0.1], ["minecraft:light_gray_wool", 1.0, 0.0], ["minecraft:light_gray_carpet", 0.5, 0.1], ["minecraft:cyan_wool", 1.0, 0.0], ["minecraft:cyan_carpet", 0.5, 0.1], ["minecraft:leather_leggings", 5.0, 5.0], ["alexsmobs:crocodile_chestplate", 6.0, 2.0], ["minecraft:leather_chestplate", 6.0, 6.0]]
	#Defines insulation items that have the special "chameleon molt" effect
	#Format: [["item_id", insulation, adaptSpeed], ["item_id", insulation, adaptSpeed], ...etc]
	#"item_id": The item's ID (i.e. "minecraft:iron_ingot"). Accepts tags with "#" (i.e. "#minecraft:wool").
	#"insulation": The amount of insulation the item provides. Will adjust to hot/cold based on the environment.
	#"adaptSpeed": The speed at which the item adapts to the current temperature. Higher values mean faster adaptation (from 0 to 1).
	"Adaptive Insulation Ingredients" = [["quark:ravager_hide", 2.0, 0.0085]]
	#Defines the items that provide insulation when worn
	#Format: [["item_id", cold, hot], ["item_id", cold, hot], ...etc]
	#"item_id": The item's ID (i.e. "minecraft:iron_ingot"). Accepts tags with "#" (i.e. "#minecraft:wool").
	#"cold": The amount of cold insulation the item provides.
	#"hot": The amount of heat insulation the item provides.
	"Insulating Armor" = [["minecraft:leather_helmet", 4.0, 4.0], ["minecraft:leather_leggings", 5.0, 5.0], ["environmental:yak_pants", 7.5, -5.0], ["alexsmobs:emu_leggings", 7.5, -5.0], ["minecraft:leather_chestplate", 6.0, 6.0], ["minecraft:leather_boots", 4.0, 4.0]]
	#Defines how many insulation slots armor pieces have
	#Format: [head, chest, legs, feet]
	"Insulation Slots" = [4, 6, 5, 4]
	#Defines wearable items that cannot be insulated
	#Format: ["item_id", "item_id", ...etc]
	"Insulation Blacklist" = []

[Consumables]
	#Defines items that affect the player's temperature when consumed
	#Format: [["item_id", amount], ["item_id", amount], ...etc]
	#Negative values are cold foods, positive values are hot foods
	"Temperature-Affecting Foods" = [["farmersdelight:melon_popsicle", -5], ["neapolitan:vanilla_ice_cream", -5], ["neapolitan:chocolate_ice_cream", -5], ["neapolitan:strawberry_ice_cream", -5], ["brewinandchewin:firey_fondue", 5], ["nethersdelight:magma_gelatin", 5]]
	#Defines how much a waterskin will change the player's body temperature by when used
	#Range: > 0
	"Waterskin Strength" = 50

