
["Fuel Items"]
	#Defines items that can be used as fuel
	#Format: [["item-id-1", amount-1], ["item-id-2", amount-2], ...etc]
	Boiler = [["minecraft:coal", 37], ["modestmining:coal_chunk", 5], ["minecraft:charcoal", 37], ["modestmining:charcoal_chunk", 5], ["modestmining:coke", 120], ["modestmining:coke_chunk", 37], ["minecraft:coal_block", 333], ["quark:charcoal_block", 333], ["modestmining:coke_block", 900], ["minecraft:magma_block", 333], ["minecraft:lava_bucket", 1000]]
	Icebox = [["minecraft:snowball", 10], ["minecraft:clay", 37], ["minecraft:snow_block", 100], ["minecraft:ice", 250], ["minecraft:packed_ice", 1000]]
	#Negative values indicate cold fuel
	Hearth = [["minecraft:coal", 37], ["modestmining:coal_chunk", 5], ["minecraft:charcoal", 37], ["modestmining:charcoal_chunk", 5], ["modestmining:coke", 120], ["modestmining:coke_chunk", 37], ["minecraft:coal_block", 333], ["quark:charcoal_block", 333], ["modestmining:coke_block", 900], ["minecraft:magma_block", 333], ["minecraft:lava_bucket", 1000], ["minecraft:snowball", -10], ["minecraft:clay", -37], ["minecraft:snow_block", -100], ["minecraft:ice", -250], ["minecraft:packed_ice", -1000]]
	#If true, potions can be used as fuel in the hearth
	#This gives all players in range the potion effect
	"Allow Potions in Hearth" = true
	#Potions containing any of these effects will not be allowed in the hearth
	#Format: ["effect_id", "effect_id", ...etc]
	"Blacklisted Hearth Potions" = ["minecraft:instant_damage", "minecraft:poison", "minecraft:wither", "minecraft:weakness", "minecraft:mining_fatigue", "minecraft:slowness"]

["Soulspring Lamp"]
	#Defines items that the Soulspring Lamp can use as fuel
	#Format: [["item-id-1", amount-1], ["item-id-2", amount-2], ...etc]
	"Fuel Items" = []
	#Defines the dimensions that the Soulspring Lamp can be used in
	#Format: ["dimension-id-1", "dimension-id-2", ...etc]
	"Valid Dimensions" = []

[Insulation]
	#Defines the items that can be used for insulating armor in the Sewing Table
	#Format: [["item_id", cold, hot, "static", *nbt], ["item_id", amount, adapt-speed, "adaptive", *nbt], ...etc]
	#"item_id": The item's ID (i.e. "minecraft:iron_ingot"). Accepts tags with "#" (i.e. "#minecraft:wool").
	#
	#Adaptive Insulation: 
	#"amount": The amount of insulation the item provides.
	#"adapt-speed": The speed at which the insulation adapts to the environment.
	#*"type": Optional. Either "static" or "adaptive". Defines the insulation type. Defaults to static.
	#*"nbt": Optional. If set, the item will only provide insulation if it has the specified NBT tag.
	#
	#Static Insulation: 
	#"cold": The amount of cold insulation the item provides.
	#"hot": The amount of heat insulation the item provides.
	#*"type": Optional. Either "static" or "adaptive". Defines the insulation type. Defaults to static.
	#*"nbt": Optional. If set, the item will only provide insulation if it has the specified NBT tag.
	"Insulation Ingredients" = [["ecologics:penguin_feather", 1.0, 0.0, "static", "{}"], ["minecraft:feather", 0.5, 0.5, "static", "{}"], ["alexsmobs:emu_feather", 0.0, 1.0, "static", "{}"], ["modestmining:fiber", 0.0, 0.5, "static", "{}"], ["alexsmobs:raccoon_tail", 0.5, 0.5, "static", "{}"], ["farmersdelight:canvas", 0.5, 0.5, "static", "{}"], ["fundamentallyfixed:cloth", 0.5, 0.5, "static", "{}"], ["minecraft:white_wool", 1.9, 0.5, "static", "{}"], ["minecraft:white_carpet", 0.5, 0.1, "static", "{}"], ["minecraft:gray_wool", 1.0, -0.5, "static", "{}"], ["minecraft:gray_carpet", 0.5, 0.1, "static", "{}"], ["fundamentallyfixed:mammal_hide", 0.5, 0.5, "static", "{}"], ["naturalist:reptile_hide", 2.0, 0.0, "static", "{}"], ["cold_sweat:goat_fur", 2.5, 0.0, "static", "{}"], ["alexsmobs:bison_fur_block", 12.0, 0.0, "static", "{}"], ["alexsmobs:bison_carpet", 5.5, 0.0, "static", "{}"], ["environmental:yak_hair", 1.0, 1.0, "static", "{}"], ["environmental:yak_hair_block", 6.0, 6.0, "static", "{}"], ["environmental:yak_hair_rug", 2.0, 2.0, "static", "{}"], ["minecraft:blue_wool", 1.0, 0.0, "static", "{}"], ["minecraft:blue_carpet", 0.5, 0.1, "static", "{}"], ["minecraft:leather", 1.5, 1.5, "static", "{}"], ["minecraft:light_blue_wool", 1.0, 0.0, "static", "{}"], ["minecraft:light_blue_carpet", 0.5, 0.1, "static", "{}"], ["cold_sweat:hoglin_hide", 0.0, 2.0, "static", "{}"], ["minecraft:leather_boots", 4.0, 4.0, "static", "{}"], ["minecraft:red_wool", 1.0, 0.0, "static", "{}"], ["minecraft:red_carpet", 0.5, 0.1, "static", "{}"], ["minecraft:leather_helmet", 4.0, 4.0, "static", "{}"], ["minecraft:yellow_wool", 1.0, 0.0, "static", "{}"], ["minecraft:yellow_carpet", 0.5, 0.1, "static", "{}"], ["minecraft:magenta_wool", 1.0, 0.0, "static", "{}"], ["minecraft:magenta_carpet", 0.5, 0.1, "static", "{}"], ["minecraft:brown_wool", 1.0, 0.0, "static", "{}"], ["minecraft:brown_carpet", 0.5, 0.1, "static", "{}"], ["minecraft:green_wool", 1.0, 0.0, "static", "{}"], ["minecraft:green_carpet", 0.5, 0.1, "static", "{}"], ["minecraft:black_wool", 1.0, -1.0, "static", "{}"], ["minecraft:black_carpet", 0.5, 0.1, "static", "{}"], ["minecraft:lime_wool", 1.0, 0.0, "static", "{}"], ["minecraft:lime_carpet", 0.5, 0.1, "static", "{}"], ["minecraft:pink_wool", 1.0, 0.0, "static", "{}"], ["minecraft:pink_carpet", 0.5, 0.1, "static", "{}"], ["minecraft:orange_wool", 1.0, 0.0, "static", "{}"], ["minecraft:orange_carpet", 0.5, 0.1, "static", "{}"], ["minecraft:purple_wool", 1.0, 0.0, "static", "{}"], ["minecraft:purple_carpet", 0.5, 0.1, "static", "{}"], ["minecraft:light_gray_wool", 1.0, 0.0, "static", "{}"], ["minecraft:light_gray_carpet", 0.5, 0.1, "static", "{}"], ["minecraft:cyan_wool", 1.0, 0.0, "static", "{}"], ["minecraft:cyan_carpet", 0.5, 0.1, "static", "{}"], ["minecraft:leather_leggings", 5.0, 5.0, "static", "{}"], ["alexsmobs:crocodile_chestplate", 6.0, 2.0, "static", "{}"], ["minecraft:leather_chestplate", 6.0, 6.0, "static", "{}"], ["cold_sweat:chameleon_molt", 2.0, 0.0085, "adaptive", "{}"]]
	#Defines the items that provide insulation when worn
	#See Insulation Ingredients for formatting
	"Insulating Armor" = [["minecraft:leather_helmet", 4.0, 4.0, "static", "{}"], ["minecraft:leather_leggings", 5.0, 5.0, "static", "{}"], ["environmental:yak_pants", 7.5, -5.0, "static", "{}"], ["alexsmobs:emu_leggings", 7.5, -5.0, "static", "{}"], ["minecraft:leather_chestplate", 6.0, 6.0, "static", "{}"], ["minecraft:leather_boots", 4.0, 4.0, "static", "{}"]]
	#Defines how many insulation slots armor pieces have
	#There are 4 modes for this setting:
	#Static: Each armor slot (head, body, legs, feet) has a fixed number of insulation slots
	#- Format: [head, body, legs, feet] (a list of integers; insulation slot count for each armor slot)
	# 
	#Linear: Number of slots increases steadily with protection
	#Exponential: Number of slots increases rapidly with protection
	#Logarithmic: Number of slots increases with protection, with diminishing returns
	#- Format: [number, max-slots] (a positive integer or decimal; the rate of increase)
	"Insulation Slots" = ["static", 4, 6, 5, 4]
	#Defines wearable items that cannot be insulated
	#Format: ["item_id", "item_id", ...etc]
	"Insulation Blacklist" = []
	#Defines the items that provide insulation when worn in a curio slot
	#See Insulation Ingredients for formatting
	"Insulating Curios" = []
	#Defines the effectiveness of insulating items in protecting against temperature
	#Range: 0.0 ~ 1.7976931348623157E308
	"Insulation Strength" = 1.0

[Consumables]
	#Defines items that affect the player's temperature when consumed
	#Format: [["item_id", amount, *nbt, *duration], ["item_id", amount, *nbt, *duration], ...etc]
	#Negative values are cold foods, positive values are hot foods
	#nbt: Optional. If set, the item will only affect the player's temperature if it has the specified NBT tag.
	#duration: Optional. If set, the player's temperature will remain increased/decreased for this amount of time (in ticks).
	"Temperature-Affecting Foods" = [["farmersdelight:melon_popsicle", -5.0, "{}"], ["neapolitan:vanilla_ice_cream", -5.0, "{}"], ["neapolitan:chocolate_ice_cream", -5.0, "{}"], ["neapolitan:strawberry_ice_cream", -5.0, "{}"], ["nethersdelight:magma_gelatin", 5.0, "{}"], ["cold_sweat:soul_sprout", 0.0, "{}", 1200]]
	#Defines how much a waterskin will change the player's body temperature by when used
	#Range: > 0
	"Waterskin Strength" = 50
	#Determines the strength of the Soulspring Lamp's effect before it is overwhelmed
	#A value of 1 means it will never be overwhelmed
	#Range: 0.0 ~ 1.0
	"Soulspring Lamp Strength" = 0.6

[Misc]
	#Defines items that affect the player's temperature when in the inventory
	#Format: [["item_id", temperature, strict_type, trait, *nbt, *max_effect], ["item_id", temperature, strict_type, trait, *nbt, *max_effect], ...etc]
	#temperature: The temperature change the item will apply to the entity. For core temperature, this is applied every tick
	#strict_type: Either "inventory", "hotbar", or "hand". Defines what slots the item must be in to apply to the entity
	#trait: The temperature trait to apply the effect to. Typical values are "core" for body temperature or "world" for ambient temperature. More on the mod documentation page.
	#nbt: Optional. The NBT data the item must have to apply to the entity.
	#max_effect: Optional. The maximum temperature effect the item can apply to the entity.
	"Carried Item Temperatures" = []

