
#Format: [["dimension_1", temperature1, *units], ["dimension_2", temperature2, *units]... etc]
#Common dimension IDs: minecraft:overworld, minecraft:the_nether, minecraft:the_end
[Dimensions]
	#Applies an offset to the world's temperature across an entire dimension
	"Dimension Temperature Offsets" = [["minecraft:the_end", -0.1, "MC"], ["minecraft:the_nether", 0.7, "MC"]]
	#Defines the temperature of a dimension, overriding all other biome and dimension temperatures/settings
	"Dimension Temperatures" = []

#Format: [["biome_1", tempLow, tempHigh, *units], ["biome_2", tempLow, tempHigh, *units]... etc]
#temp-low: The temperature of the biome at midnight
#temp-high: The temperature of the biome at noon
#units: Optional. The units of the temperature ("C" or "F". Defaults to MC units)
[Biomes]
	#Applies an offset to the temperature of a biome
	"Biome Temperature Offsets" = []
	#Defines the temperature of a biome, overriding the biome's default temperature
	"Biome Temperatures" = [["minecraft:stony_shore", 0.42857142857142855, 0.7619047619047619, "MC"], ["minecraft:savanna", 0.9047619047619048, 1.5, "MC"], ["minecraft:windswept_forest", 0.38095238095238093, 0.8095238095238095, "MC"], ["minecraft:river", 0.6666666666666666, 0.9047619047619048, "MC"], ["minecraft:old_growth_pine_taiga", 0.38095238095238093, 0.7142857142857143, "MC"], ["minecraft:deep_dark", 0.7380952380952381, 0.7380952380952381, "MC"], ["minecraft:desert", 0.38095238095238093, 1.9761904761904763, "MC"], ["minecraft:wooded_badlands", 1.1428571428571428, 1.8095238095238095, "MC"], ["minecraft:soul_sand_valley", 0.023809523809523808, 0.023809523809523808, "MC"], ["minecraft:snowy_beach", 0.14285714285714285, 0.47619047619047616, "MC"], ["minecraft:windswept_savanna", 0.8333333333333334, 1.380952380952381, "MC"], ["atmospheric:petrified_dunes", 0.6190476190476191, 2.0952380952380953, "MC"], ["minecraft:snowy_slopes", -0.19047619047619047, 0.14285714285714285, "MC"], ["minecraft:bamboo_jungle", 1.0476190476190477, 1.3095238095238095, "MC"], ["minecraft:warm_ocean", 0.8333333333333334, 1.0476190476190477, "MC"], ["minecraft:savanna_plateau", 1.0476190476190477, 1.5714285714285714, "MC"], ["minecraft:frozen_peaks", -0.40476190476190477, 0.023809523809523808, "MC"], ["environmental:marsh", 0.6666666666666666, 1.1428571428571428, "MC"], ["minecraft:snowy_taiga", -0.30952380952380953, 0.38095238095238093, "MC"], ["atmospheric:dunes", 1.0952380952380953, 1.9761904761904763, "MC"], ["minecraft:jungle", 1.0476190476190477, 1.3095238095238095, "MC"], ["minecraft:eroded_badlands", 1.3333333333333333, 2.0952380952380953, "MC"], ["minecraft:taiga", 0.2857142857142857, 0.7142857142857143, "MC"], ["atmospheric:rainforest_basin", 0.8571428571428571, 1.380952380952381, "MC"], ["atmospheric:sparse_rainforest", 0.7142857142857143, 1.2142857142857142, "MC"], ["minecraft:old_growth_spruce_taiga", 0.38095238095238093, 0.7142857142857143, "MC"], ["atmospheric:rainforest", 0.8571428571428571, 1.380952380952381, "MC"], ["atmospheric:sparse_rainforest_basin", 0.7142857142857143, 1.2142857142857142, "MC"], ["atmospheric:flourishing_dunes", 0.8571428571428571, 1.7380952380952381, "MC"], ["minecraft:deep_frozen_ocean", 0.5714285714285714, 0.7857142857142857, "MC"], ["minecraft:badlands", 1.2380952380952381, 2.0952380952380953, "MC"], ["minecraft:old_growth_birch_forest", 0.6190476190476191, 0.9523809523809523, "MC"], ["minecraft:swamp", 0.9523809523809523, 1.2380952380952381, "MC"], ["atmospheric:rocky_dunes", 0.5476190476190477, 2.2142857142857144, "MC"]]

[Misc]
	#The amount of temperature normalization from being deep underground
	#0.0 = no insulation, 1.0 = full insulation
	#Range: 0.0 ~ 1.0
	"Cave Insulation Strength" = 1.0
	#Overrides the world temperature when the player is within this structure
	#Format: [["structure_1", temperature1, *units], ["structure_2", temperature2, *units]... etc]
	#(* = optional)
	"Structure Temperatures" = [["minecraft:igloo", 65.0, "F"]]
	#Offsets the world temperature when the player is within this structure
	#Format: [["structure_1", offset1, *units], ["structure_2", offset2, *units]... etc]
	#(* = optional)
	"Structure Temperature Offsets" = []
	#List of blocks that will allow the player to sleep on them, regardless of the "Prevent Sleep When in Danger" setting
	#Use this list if the player is not getting the temperature effect from sleeping on particular blocks
	"Sleep Check Override Blocks" = []
	#When set to true, players cannot sleep if they are cold or hot enough to die
	"Check Sleeping Conditions" = true
	#Converts damage dealt by Soul Fire to cold damage (default: true)
	#Does not affect the block's temperature
	"Cold Soul Fire" = true

[Blocks]
	#Allows for adding simple BlockTemps without the use of Java mods
	#Format (All temperatures are in Minecraft units):
	#[["block-ids", <temperature>, <range>, <*max effect>, <*predicates>, <*nbt>, <*temperature-limit>], [etc...], [etc...]]
	#(* = optional) (1 °MC = 42 °F/ 23.33 °C)
	#
	#Arguments:
	#block-ids: Multiple IDs can be used by separating them with commas (i.e: "minecraft:torch,minecraft:wall_torch")
	#temperature: The temperature of the block, in Minecraft units
	#*falloff: The block is less effective as distance increases
	#*max effect: The maximum temperature change this block can cause to a player (even with multiple blocks)
	#*predicates: The state that the block has to be in for the temperature to be applied (i.e. lit=true).
	#- (Multiple predicates can be used by separating them with commas [i.e. "lit=true,waterlogged=false"])
	#*nbt: The NBT data that the block must have for the temperature to be applied.
	#*temperature-limit: The maximum world temperature at which this block temp will be effective.
	#- (Represents the minimum temp if the block temp is negative)
	"Block Temperatures" = [["cold_sweat:boiler", 0.27, 7, 0.88, "lit=true", "", 4], ["cold_sweat:icebox", -0.27, 7, 0.88, "frosted=true", "", 0], ["minecraft:fire", 0.476, 7, 0.9, "", "", 8], ["#minecraft:campfires", 0.476, 7, 0.9, "lit=true", " ", 8], ["minecraft:magma_block", 0.25, 3, 1.0], ["minecraft:lava_cauldron", 0.5, 7, 1.5], ["#minecraft:ice", -0.15, 4, 0.6, "", "", -0.7], ["minecraft:ice", -0.15, 4, 0.6, "", "{}", -0.7], ["minecraft:packed_ice", -0.25, 4, 1.0, "", "{}", -0.7], ["minecraft:blue_ice", -0.35, 4, 1.4, "", "{}", -0.7]]
	#The maximum range of blocks' area of effect
	#Note: This will not change anything unless blocks are configured to utilize the expanded range
	#This value is capped at 16 for performance reasons
	#Range: 1 ~ 16
	"Block Range" = 7
	#When set to true, uses Cold Sweat's temperature system to determine water freezing behavior
	"Custom Freezing Check" = true

[Hearth]
	#Allows the hearth to automatically turn on/off based on nearby players' temperature
	#If false, the hearth turns on/off by redstone signal
	"Automatic Hearth" = false
	#How effective the hearth is at normalizing temperature
	#Range: 0.0 ~ 1.0
	"Hearth Strength" = 0.75
	#List of additional blocks that the hearth can spread through
	#Use this list if the hearth isn't spreading through particular blocks that it should
	"Hearth Spread Whitelist" = ["minecraft:iron_bars", "minecraft:jungle_leaves", "minecraft:oak_leaves", "minecraft:spruce_leaves", "minecraft:dark_oak_leaves", "minecraft:acacia_leaves", "minecraft:birch_leaves", "minecraft:azalea_leaves", "minecraft:flowering_azalea_leaves", "minecraft:mangrove_leaves", "quark:blue_blossom_leaves", "quark:lavender_blossom_leaves", "quark:orange_blossom_leaves", "quark:pink_blossom_leaves", "quark:yellow_blossom_leaves", "quark:red_blossom_leaves", "quark:ancient_leaves", "atmospheric:rosewood_leaves", "atmospheric:morado_leaves", "atmospheric:flowering_morado_leaves", "atmospheric:yucca_leaves", "atmospheric:kousa_leaves", "atmospheric:aspen_leaves", "atmospheric:green_aspen_leaves", "atmospheric:grimwood_leaves", "atmospheric:laurel_leaves", "atmospheric:dry_laurel_leaves", "atmospheric:currant_leaves", "upgrade_aquatic:river_leaves", "autumnity:maple_leaves", "autumnity:yellow_maple_leaves", "autumnity:orange_maple_leaves", "autumnity:red_maple_leaves", "environmental:willow_leaves", "environmental:pine_leaves", "environmental:wisteria_leaves", "environmental:pink_wisteria_leaves", "environmental:blue_wisteria_leaves", "environmental:purple_wisteria_leaves", "environmental:white_wisteria_leaves", "environmental:cherry_leaves", "environmental:cheerful_cherry_leaves", "environmental:moody_cherry_leaves", "environmental:hibiscus_leaves", "windswept:holly_leaves", "windswept:chestnut_leaves", "culturaldelights:avocado_leaves", "culturaldelights:fruiting_avocado_leaves", "ecologics:coconut_leaves", "ecologics:walnut_leaves", "aether:skyroot_leaves", "aether:golden_oak_leaves", "aether:crystal_leaves", "aether:crystal_fruit_leaves", "aether:holiday_leaves", "aether:decorated_holiday_leaves", "architects_palette:twisted_leaves", "create:encased_fluid_pipe"]
	#List of additional blocks that the hearth cannot spread through
	#Use this list if the hearth is spreading through particular blocks that it shouldn't
	"Hearth Spread Blacklist" = []

